services:
  - type: web
    name: smartsociety
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: DDL_AUTO
        value: update
