package com.smartapartment.controller;

import com.fasterxml.jackson.core.type.TypeReference;import com.fasterxml.jackson.databind.ObjectMapper;
import com.smartapartment.entity.*;import com.smartapartment.repository.*;import com.smartapartment.service.*;
import jakarta.validation.Valid;import jakarta.validation.constraints.*;import java.math.BigDecimal;import java.time.*;import java.util.*;
import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.bind.annotation.*;

@RestController @RequestMapping("/api/society/advanced")
public class AdvancedSocietyApiController{
 private final CurrentUserService current;private final BillingRuleRepository rules;private final BillingService billing;private final DomesticStaffRepository staff;private final DeliveryEntryRepository deliveries;private final ApartmentRepository apartments;private final CommunityPollRepository polls;private final PollVoteRepository votes;private final SocietyAssetRepository assets;private final ObjectMapper json;
 public AdvancedSocietyApiController(CurrentUserService c,BillingRuleRepository r,BillingService b,DomesticStaffRepository s,DeliveryEntryRepository d,ApartmentRepository a,CommunityPollRepository p,PollVoteRepository v,SocietyAssetRepository x,ObjectMapper j){current=c;rules=r;billing=b;staff=s;deliveries=d;apartments=a;polls=p;votes=v;assets=x;json=j;}

 @GetMapping("/billing-rules") @PreAuthorize("hasAnyRole('SOCIETY_ADMIN','ACCOUNTANT')") public List<BillingRule> rules(){return rules.findByTenantIdOrderByNameAsc(current.requireTenantId());}
 @PostMapping("/billing-rules") @PreAuthorize("hasAnyRole('SOCIETY_ADMIN','ACCOUNTANT')") @Transactional public BillingRule rule(@Valid @RequestBody BillingRuleRequest r){BillingRule x=new BillingRule();x.setTenantId(current.requireTenantId());x.setName(r.name());x.setAmount(r.amount());x.setDueDay(r.dueDay());x.setLateFee(r.lateFee());x.setFrequency(r.frequency().toUpperCase(Locale.ROOT));x.setNextRunDate(r.nextRunDate());x.setAutomatic(r.automatic());x.setAutoCalculateLateFees(r.automatic());return rules.save(x);}
 @PatchMapping("/billing-rules/{id}") @PreAuthorize("hasAnyRole('SOCIETY_ADMIN','ACCOUNTANT')") @Transactional public BillingRule updateRule(@PathVariable Long id,@Valid @RequestBody BillingRuleRequest r){BillingRule x=rules.findByIdAndTenantId(id,current.requireTenantId()).orElseThrow(()->new IllegalArgumentException("Billing rule was not found"));x.setName(r.name());x.setAmount(r.amount());x.setDueDay(r.dueDay());x.setLateFee(r.lateFee());x.setFrequency(r.frequency().toUpperCase(Locale.ROOT));x.setNextRunDate(r.nextRunDate());x.setAutomatic(r.automatic());x.setAutoCalculateLateFees(r.automatic());return rules.save(x);}
 @DeleteMapping("/billing-rules/{id}") @PreAuthorize("hasRole('SOCIETY_ADMIN')") @Transactional public Map<String,Object> deleteRule(@PathVariable Long id){BillingRule x=rules.findByIdAndTenantId(id,current.requireTenantId()).orElseThrow(()->new IllegalArgumentException("Billing rule was not found"));rules.delete(x);return Map.of("id",id,"message","Billing rule deleted");}
 @PostMapping("/billing-rules/{id}/run") @PreAuthorize("hasAnyRole('SOCIETY_ADMIN','ACCOUNTANT')") @Transactional public Map<String,Object> runRule(@PathVariable Long id,@RequestParam(required=false)String month){BillingRule r=rules.findByIdAndTenantId(id,current.requireTenantId()).orElseThrow(()->new IllegalArgumentException("Billing rule was not found"));String cycle=month==null?YearMonth.now().toString():month;int count=billing.generateMonthlyBills(r.getTenantId(),cycle,r.getAmount());if(r.getNextRunDate()!=null)r.setNextRunDate(r.getNextRunDate().plusMonths(1));rules.save(r);return Map.of("created",count,"month",cycle);}

 @GetMapping("/staff") public List<DomesticStaff> staff(){return staff.findByTenantIdOrderByNameAsc(current.requireTenantId());}
 @PostMapping("/staff") @PreAuthorize("hasAnyRole('SOCIETY_ADMIN','SECURITY_STAFF')") @Transactional public DomesticStaff staff(@Valid @RequestBody StaffRequest r){DomesticStaff s=new DomesticStaff();s.setTenantId(current.requireTenantId());applyStaff(s,r);s.setPassCode(UUID.randomUUID().toString().substring(0,8).toUpperCase(Locale.ROOT));return staff.save(s);}
 @PatchMapping("/staff/{id}") @PreAuthorize("hasRole('SOCIETY_ADMIN')") @Transactional public DomesticStaff updateStaff(@PathVariable Long id,@Valid @RequestBody StaffRequest r){DomesticStaff s=staff.findByIdAndTenantId(id,current.requireTenantId()).orElseThrow(()->new IllegalArgumentException("Staff record was not found"));applyStaff(s,r);return staff.save(s);}
 @DeleteMapping("/staff/{id}") @PreAuthorize("hasRole('SOCIETY_ADMIN')") @Transactional public Map<String,Object> deleteStaff(@PathVariable Long id){DomesticStaff s=staff.findByIdAndTenantId(id,current.requireTenantId()).orElseThrow(()->new IllegalArgumentException("Staff record was not found"));staff.delete(s);return Map.of("id",id,"message","Staff record removed");}
 @PatchMapping("/staff/{id}/blacklist") @PreAuthorize("hasRole('SOCIETY_ADMIN')") @Transactional public DomesticStaff blacklist(@PathVariable Long id,@RequestParam boolean value){DomesticStaff s=staff.findByIdAndTenantId(id,current.requireTenantId()).orElseThrow(()->new IllegalArgumentException("Staff record was not found"));s.setBlacklisted(value);return staff.save(s);}

 @GetMapping("/deliveries") public List<Map<String,Object>> deliveries(){return deliveries.findByTenantIdOrderByArrivedAtDesc(current.requireTenantId()).stream().map(d->map("id",d.getId(),"unitNo",d.getApartment().getUnitNo(),"provider",d.getProvider(),"agentName",d.getAgentName(),"phone",d.getAgentPhone(),"packageType",d.getPackageType(),"approvalStatus",d.getApprovalStatus(),"arrivedAt",d.getArrivedAt(),"collectedAt",d.getCollectedAt(),"trackingNumber",blank(d.getTrackingNumber()),"recipientName",blank(d.getRecipientName()),"storageLocation",blank(d.getStorageLocation()),"packageCondition",blank(d.getPackageCondition()),"deliveryNotes",blank(d.getDeliveryNotes()),"photoReference",blank(d.getPhotoReference()),"collectedBy",blank(d.getCollectedBy()))).toList();}
 @PostMapping("/deliveries") @PreAuthorize("hasAnyRole('SOCIETY_ADMIN','SECURITY_STAFF')") @Transactional public Map<String,Object> delivery(@Valid @RequestBody DeliveryRequest r){String t=current.requireTenantId();DeliveryEntry d=new DeliveryEntry();d.setTenantId(t);applyDelivery(d,r,t);d.setApprovalStatus("WAITING_COLLECTION");d.setArrivedAt(LocalDateTime.now());d=deliveries.save(d);return map("id",d.getId(),"message","Delivery recorded");}
 @PatchMapping("/deliveries/{id}") @PreAuthorize("hasAnyRole('SOCIETY_ADMIN','SECURITY_STAFF')") @Transactional public Map<String,Object> updateDelivery(@PathVariable Long id,@Valid @RequestBody DeliveryRequest r){String t=current.requireTenantId();DeliveryEntry d=deliveries.findByIdAndTenantId(id,t).orElseThrow(()->new IllegalArgumentException("Delivery was not found"));applyDelivery(d,r,t);deliveries.save(d);return map("id",id,"message","Delivery updated");}
 @DeleteMapping("/deliveries/{id}") @PreAuthorize("hasRole('SOCIETY_ADMIN')") @Transactional public Map<String,Object> deleteDelivery(@PathVariable Long id){DeliveryEntry d=deliveries.findByIdAndTenantId(id,current.requireTenantId()).orElseThrow(()->new IllegalArgumentException("Delivery was not found"));deliveries.delete(d);return map("id",id,"message","Delivery removed");}
 @PatchMapping("/deliveries/{id}/collect") @Transactional public Map<String,Object> collect(@PathVariable Long id){DeliveryEntry d=deliveries.findByIdAndTenantId(id,current.requireTenantId()).orElseThrow(()->new IllegalArgumentException("Delivery was not found"));d.setCollectedAt(LocalDateTime.now());d.setCollectedBy(current.requireUser().getFullName());d.setApprovalStatus("COLLECTED");deliveries.save(d);return map("id",id,"message","Delivery collected");}

 @GetMapping("/polls") public List<Map<String,Object>> polls(){AppUser u=current.requireUser();return polls.findByTenantIdOrderByCreatedAtDesc(u.getTenantId()).stream().map(p->pollView(p,u)).toList();}
 @PostMapping("/polls") @PreAuthorize("hasRole('SOCIETY_ADMIN')") @Transactional public Map<String,Object> poll(@Valid @RequestBody PollRequest r){CommunityPoll p=new CommunityPoll();p.setTenantId(current.requireTenantId());p.setQuestion(r.question());try{p.setOptionsJson(json.writeValueAsString(r.options()));}catch(Exception e){throw new IllegalArgumentException("Poll options are invalid");}p.setClosesAt(r.closesAt());p.setAnonymous(r.anonymous());p.setDescription(blank(r.description()));p.setCategory(blank(r.category()));p.setAudience(blank(r.audience()).isBlank()?"RESIDENTS":blank(r.audience()).toUpperCase(Locale.ROOT));p.setResultsVisible(r.resultsVisible());p=polls.save(p);return map("id",p.getId(),"message","Poll published");}
 @PatchMapping("/polls/{id}/close") @PreAuthorize("hasRole('SOCIETY_ADMIN')") @Transactional public Map<String,Object> closePoll(@PathVariable Long id){CommunityPoll p=polls.findByIdAndTenantId(id,current.requireTenantId()).orElseThrow(()->new IllegalArgumentException("Poll was not found"));p.setClosesAt(LocalDateTime.now());polls.save(p);return map("id",id,"message","Poll closed");}
 @DeleteMapping("/polls/{id}") @PreAuthorize("hasRole('SOCIETY_ADMIN')") @Transactional public Map<String,Object> deletePoll(@PathVariable Long id){CommunityPoll p=polls.findByIdAndTenantId(id,current.requireTenantId()).orElseThrow(()->new IllegalArgumentException("Poll was not found"));polls.delete(p);return map("id",id,"message","Poll removed");}
 @PostMapping("/polls/{id}/vote") @PreAuthorize("hasRole('RESIDENT')") @Transactional public Map<String,Object> vote(@PathVariable Long id,@RequestParam @PositiveOrZero int option){AppUser u=current.requireUser();CommunityPoll p=polls.findByIdAndTenantId(id,u.getTenantId()).orElseThrow(()->new IllegalArgumentException("Poll was not found"));List<String> choices=options(p);if(p.getClosesAt()!=null&&p.getClosesAt().isBefore(LocalDateTime.now()))throw new IllegalArgumentException("Poll is closed");if(option>=choices.size())throw new IllegalArgumentException("Poll option is invalid");PollVote v=votes.findByTenantIdAndPollIdAndUserId(u.getTenantId(),id,u.getId()).orElseGet(PollVote::new);v.setTenantId(u.getTenantId());v.setPoll(p);v.setUser(u);v.setOptionIndex(option);votes.save(v);return map("message","Vote recorded","option",option);}

 @GetMapping("/assets") @PreAuthorize("hasAnyRole('SOCIETY_ADMIN','MAINTENANCE_STAFF','ACCOUNTANT','FACILITY_MANAGER')") public List<SocietyAsset> assets(){return assets.findByTenantIdOrderByNameAsc(current.requireTenantId());}
 @PostMapping("/assets") @PreAuthorize("hasAnyRole('SOCIETY_ADMIN','FACILITY_MANAGER')") @Transactional public SocietyAsset asset(@Valid @RequestBody AssetRequest r){SocietyAsset a=new SocietyAsset();a.setTenantId(current.requireTenantId());applyAsset(a,r);return assets.save(a);}
 @PatchMapping("/assets/{id}") @PreAuthorize("hasAnyRole('SOCIETY_ADMIN','FACILITY_MANAGER')") @Transactional public SocietyAsset updateAsset(@PathVariable Long id,@Valid @RequestBody AssetRequest r){SocietyAsset a=assets.findByIdAndTenantId(id,current.requireTenantId()).orElseThrow(()->new IllegalArgumentException("Asset was not found"));applyAsset(a,r);return assets.save(a);}
 @DeleteMapping("/assets/{id}") @PreAuthorize("hasRole('SOCIETY_ADMIN')") @Transactional public Map<String,Object> deleteAsset(@PathVariable Long id){SocietyAsset a=assets.findByIdAndTenantId(id,current.requireTenantId()).orElseThrow(()->new IllegalArgumentException("Asset was not found"));assets.delete(a);return map("id",id,"message","Asset removed");}
 @PatchMapping("/assets/{id}/service") @PreAuthorize("hasAnyRole('SOCIETY_ADMIN','MAINTENANCE_STAFF','FACILITY_MANAGER')") @Transactional public SocietyAsset service(@PathVariable Long id,@RequestParam @Future LocalDate nextDate){SocietyAsset a=assets.findByIdAndTenantId(id,current.requireTenantId()).orElseThrow(()->new IllegalArgumentException("Asset was not found"));a.setLastServiceDate(LocalDate.now());a.setNextServiceDate(nextDate);return assets.save(a);}

 private Map<String,Object> pollView(CommunityPoll p,AppUser u){List<String> choices=options(p);long[] counts=new long[choices.size()];for(PollVote v:votes.findByTenantIdAndPollId(u.getTenantId(),p.getId()))if(v.getOptionIndex()>=0&&v.getOptionIndex()<counts.length)counts[v.getOptionIndex()]++;Integer selected=votes.findByTenantIdAndPollIdAndUserId(u.getTenantId(),p.getId(),u.getId()).map(PollVote::getOptionIndex).orElse(null);return map("id",p.getId(),"question",p.getQuestion(),"options",choices,"counts",counts,"closesAt",p.getClosesAt(),"anonymous",p.isAnonymous(),"selectedOption",selected,"description",blank(p.getDescription()),"category",blank(p.getCategory()),"audience",blank(p.getAudience()),"resultsVisible",p.isResultsVisible(),"createdAt",p.getCreatedAt(),"totalVotes",Arrays.stream(counts).sum(),"closed",p.getClosesAt()!=null&&p.getClosesAt().isBefore(LocalDateTime.now()));}
 private List<String> options(CommunityPoll p){try{return json.readValue(p.getOptionsJson(),new TypeReference<>(){});}catch(Exception e){return List.of();}}
 private static Map<String,Object> map(Object...v){Map<String,Object>m=new LinkedHashMap<>();for(int i=0;i<v.length;i+=2)m.put((String)v[i],v[i+1]);return m;}
 private void applyStaff(DomesticStaff s,StaffRequest r){s.setName(r.name().trim());s.setPhone(r.phone().trim());s.setServiceType(r.serviceType().trim());s.setIdentityStatus(r.identityStatus().trim().toUpperCase(Locale.ROOT));s.setAssignedArea(blank(r.assignedArea()));s.setEmergencyContact(blank(r.emergencyContact()));s.setWorkingDays(blank(r.workingDays()));s.setShiftStart(blank(r.shiftStart()));s.setShiftEnd(blank(r.shiftEnd()));s.setNotes(blank(r.notes()));s.setAddressProof(blank(r.addressProof()));}
 private void applyDelivery(DeliveryEntry d,DeliveryRequest r,String tenantId){Apartment a=apartments.findFirstByTenantIdAndUnitNoOrderByIdAsc(tenantId,r.unitNo()).orElseThrow(()->new IllegalArgumentException("Apartment was not found"));d.setApartment(a);d.setProvider(r.provider().trim());d.setAgentName(blank(r.agentName()));d.setAgentPhone(blank(r.phone()));d.setPackageType(r.packageType().trim().toUpperCase(Locale.ROOT));d.setTrackingNumber(blank(r.trackingNumber()));d.setRecipientName(blank(r.recipientName()));d.setStorageLocation(blank(r.storageLocation()));d.setPackageCondition(blank(r.packageCondition()));d.setDeliveryNotes(blank(r.deliveryNotes()));d.setPhotoReference(blank(r.photoReference()));}
 private void applyAsset(SocietyAsset a,AssetRequest r){a.setName(r.name().trim());a.setCategory(r.category().trim());a.setLocation(r.location().trim());a.setSerialNumber(blank(r.serialNumber()));a.setPurchasedOn(r.purchasedOn());a.setPurchaseCost(r.purchaseCost());a.setWarrantyUntil(r.warrantyUntil());a.setNextServiceDate(r.nextServiceDate());a.setVendorId(r.vendorId());a.setVendorName(blank(r.vendorName()));a.setVendorPhone(blank(r.vendorPhone()));a.setAmcProvider(blank(r.amcProvider()));a.setAmcUntil(r.amcUntil());a.setLastServiceDate(r.lastServiceDate());a.setServiceIntervalDays(r.serviceIntervalDays());a.setAssetCondition(blank(r.assetCondition()).isBlank()?"GOOD":blank(r.assetCondition()).toUpperCase(Locale.ROOT));a.setNotes(blank(r.notes()));}
 private static String blank(String value){return value==null?"":value.trim();}
 public record BillingRuleRequest(@NotBlank String name,@NotNull @Positive BigDecimal amount,@Min(1)@Max(28)int dueDay,@NotNull@PositiveOrZero BigDecimal lateFee,@NotBlank String frequency,LocalDate nextRunDate,boolean automatic){}
 public record StaffRequest(@NotBlank String name,@NotBlank String phone,@NotBlank String serviceType,@NotBlank String identityStatus,String assignedArea,String emergencyContact,String workingDays,String shiftStart,String shiftEnd,String notes,String addressProof){}
 public record DeliveryRequest(@NotBlank String unitNo,@NotBlank String provider,String agentName,String phone,@NotBlank String packageType,String trackingNumber,String recipientName,String storageLocation,String packageCondition,String deliveryNotes,String photoReference){}
 public record PollRequest(@NotBlank String question,@Size(min=2,max=8)List<@NotBlank String> options,@NotNull@Future LocalDateTime closesAt,boolean anonymous,String description,String category,String audience,boolean resultsVisible){}
 public record AssetRequest(@NotBlank String name,@NotBlank String category,@NotBlank String location,String serialNumber,LocalDate purchasedOn,@PositiveOrZero BigDecimal purchaseCost,LocalDate warrantyUntil,LocalDate nextServiceDate,Long vendorId,String vendorName,String vendorPhone,String amcProvider,LocalDate amcUntil,LocalDate lastServiceDate,@Min(1)@Max(3650) Integer serviceIntervalDays,String assetCondition,String notes){}
}
