package com.smartapartment.controller;
import com.smartapartment.entity.*;import com.smartapartment.repository.*;import jakarta.servlet.http.HttpSession;import jakarta.validation.Valid;import jakarta.validation.constraints.*;import java.math.BigDecimal;import java.time.*;import java.util.*;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/property")
public class PropertyApiController{
 private final PropertyListingRepository listings;private final PropertyEnquiryRepository enquiries;private final SavedPropertyRepository saved;private final SavedSearchRepository searches;private final PropertyVisitRepository visits;private final PropertyServiceRequestRepository services;
 public PropertyApiController(PropertyListingRepository l,PropertyEnquiryRepository e,SavedPropertyRepository s,SavedSearchRepository q,PropertyVisitRepository v,PropertyServiceRequestRepository r){listings=l;enquiries=e;saved=s;searches=q;visits=v;services=r;}
 @GetMapping("/listings") public List<PropertyListing> listings(@RequestParam(required=false)String city,@RequestParam(required=false)String locality,@RequestParam(required=false)String type,@RequestParam(required=false)String bhk,@RequestParam(required=false)BigDecimal minPrice,@RequestParam(required=false)BigDecimal maxPrice,@RequestParam(required=false)String furnishing,@RequestParam(defaultValue="newest")String sort){java.util.stream.Stream<PropertyListing>s=listings.findByStatusOrderByCreatedAtDesc("ACTIVE").stream().filter(x->blank(city)||eq(x.getCity(),city)).filter(x->blank(locality)||contains(x.getLocality(),locality)||contains(x.getSociety(),locality)).filter(x->blank(type)||eq(x.getListingType(),type)).filter(x->blank(bhk)||eq(x.getBhk(),bhk)).filter(x->minPrice==null||x.getPrice().compareTo(minPrice)>=0).filter(x->maxPrice==null||x.getPrice().compareTo(maxPrice)<=0).filter(x->blank(furnishing)||eq(x.getFurnishing(),furnishing));Comparator<PropertyListing>c="price_asc".equals(sort)?Comparator.comparing(PropertyListing::getPrice):"price_desc".equals(sort)?Comparator.comparing(PropertyListing::getPrice).reversed():Comparator.comparing(PropertyListing::getCreatedAt).reversed();return s.sorted(c).toList();}
 @GetMapping("/listings/{id}") @Transactional public PropertyListing listing(@PathVariable Long id){PropertyListing l=listings.findById(id).filter(x->"ACTIVE".equals(x.getStatus())).orElseThrow(()->new IllegalArgumentException("Listing was not found"));l.setViewCount(l.getViewCount()+1);return listings.save(l);}
 @GetMapping("/my-listings") public List<PropertyListing> mine(HttpSession s){return listings.findByCustomerIdOrderByCreatedAtDesc(customer(s));}
 @PostMapping("/listings") @Transactional public PropertyListing create(@Valid @RequestBody ListingRequest r,HttpSession s){PropertyListing l=new PropertyListing();l.setTenantId("propertydirect");l.setCustomerId(customer(s));l.setTitle(r.title());l.setSociety(r.society());l.setLocality(r.locality());l.setCity(r.city());l.setListingType(r.type().toUpperCase(Locale.ROOT));l.setPropertyType(text(r.propertyType(),"APARTMENT"));l.setPrice(r.price());l.setDeposit(r.deposit());l.setMaintenance(r.maintenance());l.setAreaSqft(r.areaSqft());l.setBhk(r.bhk());l.setFurnishing(r.furnishing());l.setParking(r.parking());l.setAvailableFrom(r.availableFrom());l.setLatitude(r.latitude());l.setLongitude(r.longitude());l.setAmenities(r.amenities());l.setImageUrl(r.imageUrl());l.setNotes(r.notes());l.setVerificationStatus("PENDING");l.setStatus("ACTIVE");return listings.save(l);}
 @DeleteMapping("/listings/{id}") @Transactional public void delete(@PathVariable Long id,HttpSession s){PropertyListing l=listings.findByIdAndCustomerId(id,customer(s)).orElseThrow(()->new IllegalArgumentException("Listing was not found"));l.setStatus("INACTIVE");listings.save(l);}
 @PostMapping("/enquiries") @Transactional public Map<String,Object> enquire(@Valid @RequestBody EnquiryRequest r,HttpSession s){PropertyEnquiry e=new PropertyEnquiry();e.setTenantId("propertydirect");e.setCustomerId((Long)s.getAttribute("propertydirect:customerId"));e.setListingId(r.listingId());e.setName(r.name());e.setPhone(r.phone());e.setEmail(r.email());e.setEnquiryType(r.type());e.setMessage(r.message());e=enquiries.save(e);return Map.of("id",e.getId(),"message","Enquiry submitted");}
 @GetMapping("/saved") public List<SavedProperty> saved(HttpSession s){return saved.findByCustomerIdOrderByCreatedAtDesc(customer(s));}
 @PostMapping("/saved/{listingId}") @Transactional public Map<String,Object> save(@PathVariable Long listingId,HttpSession s){long c=customer(s);PropertyListing l=listings.findById(listingId).orElseThrow(()->new IllegalArgumentException("Listing was not found"));SavedProperty x=saved.findByCustomerIdAndListingId(c,listingId).orElseGet(SavedProperty::new);x.setTenantId("propertydirect");x.setCustomerId(c);x.setListing(l);saved.save(x);return Map.of("message","Property shortlisted");}
 @DeleteMapping("/saved/{listingId}") @Transactional public void unsave(@PathVariable Long listingId,HttpSession s){saved.findByCustomerIdAndListingId(customer(s),listingId).ifPresent(saved::delete);}
 @GetMapping("/saved-searches") public List<SavedSearch> searches(HttpSession s){return searches.findByCustomerIdOrderByCreatedAtDesc(customer(s));}
 @PostMapping("/saved-searches") @Transactional public SavedSearch search(@Valid @RequestBody SavedSearchRequest r,HttpSession s){SavedSearch x=new SavedSearch();x.setTenantId("propertydirect");x.setCustomerId(customer(s));x.setName(r.name());x.setCity(r.city());x.setLocality(r.locality());x.setListingType(r.type());x.setBhk(r.bhk());x.setMinPrice(r.minPrice());x.setMaxPrice(r.maxPrice());x.setAlertsEnabled(r.alertsEnabled());return searches.save(x);}
 @GetMapping("/visits") public List<PropertyVisit> visits(HttpSession s){return visits.findByCustomerIdOrderByScheduledAtDesc(customer(s));}
 @PostMapping("/visits") @Transactional public PropertyVisit visit(@Valid @RequestBody VisitRequest r,HttpSession s){PropertyListing l=listings.findById(r.listingId()).orElseThrow(()->new IllegalArgumentException("Listing was not found"));PropertyVisit v=new PropertyVisit();v.setTenantId("propertydirect");v.setCustomerId(customer(s));v.setListing(l);v.setScheduledAt(r.scheduledAt());v.setVisitStatus("REQUESTED");v.setNotes(r.notes());return visits.save(v);}
 @GetMapping("/services") public List<PropertyServiceRequest> services(HttpSession s){return services.findByCustomerIdOrderByCreatedAtDesc(customer(s));}
 @PostMapping("/services") @Transactional public PropertyServiceRequest service(@Valid @RequestBody ServiceRequest r,HttpSession s){PropertyServiceRequest x=new PropertyServiceRequest();x.setTenantId("propertydirect");x.setCustomerId(customer(s));x.setListingId(r.listingId());x.setServiceType(r.serviceType());x.setPreferredAt(r.preferredAt());x.setDetails(r.details());x.setRequestStatus("REQUESTED");return services.save(x);}
 @PatchMapping("/listings/{id}/verification") @Transactional public PropertyListing verify(@PathVariable Long id,@RequestParam String status,HttpSession s){if(!Boolean.TRUE.equals(s.getAttribute("dashboard:propertydirect:admin"))&&!Boolean.TRUE.equals(s.getAttribute("dashboard:propertydirect:superadmin")))throw new IllegalStateException("Property administrator login is required");PropertyListing l=listings.findById(id).orElseThrow(()->new IllegalArgumentException("Listing was not found"));l.setVerificationStatus(status.toUpperCase(Locale.ROOT));return listings.save(l);}
 private long customer(HttpSession s){Object id=s.getAttribute("propertydirect:customerId");if(!(id instanceof Long value))throw new IllegalStateException("PropertyDirect customer login is required");return value;}
 private static boolean blank(String v){return v==null||v.isBlank();}private static boolean eq(String a,String b){return a!=null&&a.equalsIgnoreCase(b);}private static boolean contains(String a,String b){return a!=null&&a.toLowerCase(Locale.ROOT).contains(b.toLowerCase(Locale.ROOT));}private static String text(String v,String d){return blank(v)?d:v;}
 public record ListingRequest(@NotBlank String title,@NotBlank String society,@NotBlank String locality,@NotBlank String city,@NotBlank String type,String propertyType,@NotNull @Positive BigDecimal price,@PositiveOrZero BigDecimal deposit,@PositiveOrZero BigDecimal maintenance,@Positive Integer areaSqft,@NotBlank String bhk,String furnishing,String parking,LocalDate availableFrom,Double latitude,Double longitude,String amenities,String imageUrl,String notes){}
 public record EnquiryRequest(Long listingId,@NotBlank String name,@NotBlank String phone,@Email @NotBlank String email,@NotBlank String type,String message){}
 public record SavedSearchRequest(@NotBlank String name,String city,String locality,String type,String bhk,@PositiveOrZero BigDecimal minPrice,@PositiveOrZero BigDecimal maxPrice,boolean alertsEnabled){}
 public record VisitRequest(@NotNull Long listingId,@NotNull@Future LocalDateTime scheduledAt,String notes){}
 public record ServiceRequest(Long listingId,@NotBlank String serviceType,@NotNull@Future LocalDateTime preferredAt,String details){}
}
