package com.smartapartment.controller;
import com.fasterxml.jackson.databind.ObjectMapper;import com.smartapartment.entity.*;import com.smartapartment.repository.*;import jakarta.servlet.http.HttpSession;import jakarta.validation.Valid;import jakarta.validation.constraints.*;import java.io.*;import java.math.BigDecimal;import java.nio.file.*;import java.time.*;import java.util.*;import org.springframework.core.io.*;import org.springframework.http.*;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.bind.annotation.*;import org.springframework.web.multipart.MultipartFile;
@RestController @RequestMapping("/api/property")
public class PropertyApiController{
 private final PropertyListingRepository listings;private final PropertyCustomerRepository customers;private final PropertyEnquiryRepository enquiries;private final SavedPropertyRepository saved;private final SavedSearchRepository searches;private final PropertyVisitRepository visits;private final PropertyServiceRequestRepository services;private final ObjectMapper mapper;private final Path mediaRoot=Paths.get(System.getProperty("java.io.tmpdir"),"propertydirect-media");
 public PropertyApiController(PropertyListingRepository l,PropertyCustomerRepository c,PropertyEnquiryRepository e,SavedPropertyRepository s,SavedSearchRepository q,PropertyVisitRepository v,PropertyServiceRequestRepository r,ObjectMapper m){listings=l;customers=c;enquiries=e;saved=s;searches=q;visits=v;services=r;mapper=m;}
 @GetMapping("/listings") public List<PropertyListing> listings(@RequestParam(required=false)String city,@RequestParam(required=false)String locality,@RequestParam(required=false)String type,@RequestParam(required=false)String bhk,@RequestParam(required=false)BigDecimal minPrice,@RequestParam(required=false)BigDecimal maxPrice,@RequestParam(required=false)String furnishing,@RequestParam(defaultValue="newest")String sort){java.util.stream.Stream<PropertyListing>s=listings.findByStatusAndVerificationStatusOrderByCreatedAtDesc("ACTIVE","VERIFIED").stream().filter(x->blank(city)||eq(x.getCity(),city)).filter(x->blank(locality)||contains(x.getLocality(),locality)||contains(x.getSociety(),locality)).filter(x->blank(type)||eq(x.getListingType(),type)).filter(x->blank(bhk)||eq(x.getBhk(),bhk)).filter(x->minPrice==null||x.getPrice().compareTo(minPrice)>=0).filter(x->maxPrice==null||x.getPrice().compareTo(maxPrice)<=0).filter(x->blank(furnishing)||eq(x.getFurnishing(),furnishing));Comparator<PropertyListing>c="price_asc".equals(sort)?Comparator.comparing(PropertyListing::getPrice):"price_desc".equals(sort)?Comparator.comparing(PropertyListing::getPrice).reversed():Comparator.comparing(PropertyListing::getCreatedAt).reversed();return s.sorted(c).toList();}
 @GetMapping("/listings/{id}") @Transactional public PropertyListing listing(@PathVariable Long id){PropertyListing l=listings.findById(id).filter(x->"ACTIVE".equals(x.getStatus())&&"VERIFIED".equals(x.getVerificationStatus())).orElseThrow(()->new IllegalArgumentException("Listing was not found"));l.setViewCount(l.getViewCount()+1);return listings.save(l);}
 @GetMapping("/my-listings") public List<PropertyListing> mine(HttpSession s){return listings.findByCustomerIdOrderByCreatedAtDesc(customer(s));}
 @PostMapping("/listings") @Transactional public PropertyListing create(@Valid @RequestBody ListingRequest r,HttpSession s){return saveListing(r,customer(s),List.of());}
 @PostMapping(value="/listings/with-photos",consumes=MediaType.MULTIPART_FORM_DATA_VALUE) @Transactional public PropertyListing createWithPhotos(@RequestPart("listing")String json,@RequestPart("photos")List<MultipartFile> photos,HttpSession s)throws IOException{if(photos.size()<10)throw new IllegalArgumentException("Upload at least 10 property photos");if(photos.size()>20)throw new IllegalArgumentException("A maximum of 20 property photos is allowed");ListingRequest r=mapper.readValue(json,ListingRequest.class);return saveListing(r,customer(s),photos);}
 private PropertyListing saveListing(ListingRequest r,long customerId,List<MultipartFile> photos){PropertyListing l=new PropertyListing();l.setTenantId("propertydirect");l.setCustomerId(customerId);l.setTitle(r.title());l.setSociety(r.society());l.setLocality(r.locality());l.setCity(r.city());l.setListingType(r.type().toUpperCase(Locale.ROOT));l.setPropertyType(text(r.propertyType(),"APARTMENT"));l.setPrice(r.price());l.setDeposit(r.deposit());l.setMaintenance(r.maintenance());l.setAreaSqft(r.areaSqft());l.setBhk(r.bhk());l.setFurnishing(r.furnishing());l.setParking(r.parking());l.setAvailableFrom(r.availableFrom());l.setLatitude(r.latitude());l.setLongitude(r.longitude());l.setAmenities(r.amenities());l.setNotes(r.notes());l.setVerificationStatus("PENDING");l.setStatus("PENDING_APPROVAL");l=listings.save(l);if(!photos.isEmpty()){try{Files.createDirectories(mediaRoot);List<String>urls=new ArrayList<>();for(MultipartFile photo:photos){if(photo.isEmpty()||photo.getContentType()==null||!photo.getContentType().startsWith("image/"))throw new IllegalArgumentException("Every uploaded file must be an image");String ext=Optional.ofNullable(photo.getOriginalFilename()).filter(n->n.contains(".")).map(n->n.substring(n.lastIndexOf('.'))).orElse(".jpg");String name=l.getId()+"-"+UUID.randomUUID()+ext.replaceAll("[^A-Za-z0-9.]","");Files.copy(photo.getInputStream(),mediaRoot.resolve(name),StandardCopyOption.REPLACE_EXISTING);urls.add("/api/property/media/"+name);}l.setImageUrls(String.join("\n",urls));l.setImageUrl(urls.get(0));l=listings.save(l);}catch(IOException ex){throw new UncheckedIOException(ex);}}return l;}
 @GetMapping("/media/{name:.+}") public ResponseEntity<Resource>media(@PathVariable String name)throws IOException{Path file=mediaRoot.resolve(name).normalize();if(!file.startsWith(mediaRoot)||!Files.exists(file))return ResponseEntity.notFound().build();String type=Optional.ofNullable(Files.probeContentType(file)).orElse("image/jpeg");return ResponseEntity.ok().contentType(MediaType.parseMediaType(type)).cacheControl(CacheControl.maxAge(java.time.Duration.ofDays(30))).body(new FileSystemResource(file));}
 @GetMapping("/admin/summary") public Map<String,Object>adminSummary(HttpSession s){administrator(s);return Map.of("registeredCustomers",customers.count(),"pendingListings",listings.findByVerificationStatusOrderByCreatedAtDesc("PENDING").size(),"approvedListings",listings.findByStatusAndVerificationStatusOrderByCreatedAtDesc("ACTIVE","VERIFIED").size());}
 @GetMapping("/admin/customers") public List<Map<String,Object>>adminCustomers(HttpSession s){administrator(s);return customers.findAll().stream().sorted(Comparator.comparing(PropertyCustomer::getCreatedAt,Comparator.nullsLast(Comparator.reverseOrder()))).map(c->Map.<String,Object>of("id",c.getId(),"name",text(c.getName(),"Customer"),"email",text(c.getEmail(),"—"),"phone",text(c.getPhone(),"—"),"username",text(c.getUsername(),"—"),"registeredAt",c.getCreatedAt()==null?"":c.getCreatedAt().toString(),"listingCount",listings.findByCustomerIdOrderByCreatedAtDesc(c.getId()).size())).toList();}
 @GetMapping("/admin/listings") public List<PropertyListing>adminListings(@RequestParam(defaultValue="PENDING")String verificationStatus,HttpSession s){administrator(s);return listings.findByVerificationStatusOrderByCreatedAtDesc(verificationStatus.toUpperCase(Locale.ROOT));}
 @DeleteMapping("/listings/{id}") @Transactional public void delete(@PathVariable Long id,HttpSession s){PropertyListing l=listings.findByIdAndCustomerId(id,customer(s)).orElseThrow(()->new IllegalArgumentException("Listing was not found"));l.setStatus("INACTIVE");listings.save(l);}
 @PostMapping("/enquiries") @Transactional public Map<String,Object> enquire(@Valid @RequestBody EnquiryRequest r,HttpSession s){PropertyEnquiry e=new PropertyEnquiry();e.setTenantId("propertydirect");e.setCustomerId((Long)s.getAttribute("propertydirect:customerId"));e.setListingId(r.listingId());e.setName(r.name());e.setPhone(r.phone());e.setEmail(r.email());e.setEnquiryType(r.type());e.setMessage(r.message());e=enquiries.save(e);return Map.of("id",e.getId(),"message","Enquiry submitted");}
 @PostMapping("/contact-messages") @Transactional public Map<String,Object> contact(@Valid @RequestBody ContactMessageRequest r,HttpSession s){PropertyEnquiry e=new PropertyEnquiry();e.setTenantId("propertydirect");e.setCustomerId((Long)s.getAttribute("propertydirect:customerId"));e.setName((r.firstName().trim()+" "+r.lastName().trim()).trim());e.setPhone(r.phone().trim());e.setEmail(r.email().trim().toLowerCase(Locale.ROOT));e.setEnquiryType("PLATFORM_CONTACT");e.setMessage(r.message().trim());e=enquiries.save(e);return Map.of("id",e.getId(),"message","Your message was sent to the PropertyDirect Super Admin");}
 @GetMapping("/admin/contact-messages") public List<Map<String,Object>>contactMessages(HttpSession s){administrator(s);return enquiries.findByEnquiryTypeOrderByCreatedAtDesc("PLATFORM_CONTACT").stream().map(e->{Map<String,Object>m=new LinkedHashMap<>();m.put("id",e.getId());m.put("name",text(e.getName(),"Website visitor"));m.put("email",text(e.getEmail(),"—"));m.put("phone",text(e.getPhone(),"—"));m.put("message",text(e.getMessage(),"—"));m.put("createdAt",e.getCreatedAt()==null?"":e.getCreatedAt().toString());return m;}).toList();}
 @GetMapping("/saved") public List<SavedProperty> saved(HttpSession s){return saved.findByCustomerIdOrderByCreatedAtDesc(customer(s));}
 @PostMapping("/saved/{listingId}") @Transactional public Map<String,Object> save(@PathVariable Long listingId,HttpSession s){long c=customer(s);PropertyListing l=listings.findById(listingId).orElseThrow(()->new IllegalArgumentException("Listing was not found"));SavedProperty x=saved.findByCustomerIdAndListingId(c,listingId).orElseGet(SavedProperty::new);x.setTenantId("propertydirect");x.setCustomerId(c);x.setListing(l);saved.save(x);return Map.of("message","Property shortlisted");}
 @DeleteMapping("/saved/{listingId}") @Transactional public void unsave(@PathVariable Long listingId,HttpSession s){saved.findByCustomerIdAndListingId(customer(s),listingId).ifPresent(saved::delete);}
 @GetMapping("/saved-searches") public List<SavedSearch> searches(HttpSession s){return searches.findByCustomerIdOrderByCreatedAtDesc(customer(s));}
 @PostMapping("/saved-searches") @Transactional public SavedSearch search(@Valid @RequestBody SavedSearchRequest r,HttpSession s){SavedSearch x=new SavedSearch();x.setTenantId("propertydirect");x.setCustomerId(customer(s));x.setName(r.name());x.setCity(r.city());x.setLocality(r.locality());x.setListingType(r.type());x.setBhk(r.bhk());x.setMinPrice(r.minPrice());x.setMaxPrice(r.maxPrice());x.setAlertsEnabled(r.alertsEnabled());return searches.save(x);}
 @GetMapping("/visits") public List<PropertyVisit> visits(HttpSession s){return visits.findByCustomerIdOrderByScheduledAtDesc(customer(s));}
 @PostMapping("/visits") @Transactional public PropertyVisit visit(@Valid @RequestBody VisitRequest r,HttpSession s){PropertyListing l=listings.findById(r.listingId()).orElseThrow(()->new IllegalArgumentException("Listing was not found"));PropertyVisit v=new PropertyVisit();v.setTenantId("propertydirect");v.setCustomerId(customer(s));v.setListing(l);v.setScheduledAt(r.scheduledAt());v.setVisitStatus("REQUESTED");v.setNotes(r.notes());return visits.save(v);}
 @GetMapping("/services") public List<PropertyServiceRequest> services(HttpSession s){return services.findByCustomerIdOrderByCreatedAtDesc(customer(s));}
 @PostMapping("/services") @Transactional public PropertyServiceRequest service(@Valid @RequestBody ServiceRequest r,HttpSession s){PropertyServiceRequest x=new PropertyServiceRequest();x.setTenantId("propertydirect");x.setCustomerId(customer(s));x.setListingId(r.listingId());x.setServiceType(r.serviceType());x.setPreferredAt(r.preferredAt());x.setDetails(r.details());x.setRequestStatus("REQUESTED");return services.save(x);}
 @PatchMapping("/listings/{id}/verification") @Transactional public PropertyListing verify(@PathVariable Long id,@RequestParam String status,HttpSession s){administrator(s);PropertyListing l=listings.findById(id).orElseThrow(()->new IllegalArgumentException("Listing was not found"));String decision=status.toUpperCase(Locale.ROOT);l.setVerificationStatus(decision);l.setStatus("VERIFIED".equals(decision)?"ACTIVE":"REJECTED".equals(decision)?"REJECTED":"PENDING_APPROVAL");return listings.save(l);}
 private long customer(HttpSession s){Object id=s.getAttribute("propertydirect:customerId");if(!(id instanceof Long value))throw new IllegalStateException("PropertyDirect customer login is required");return value;}
 private void administrator(HttpSession s){if(!Boolean.TRUE.equals(s.getAttribute("dashboard:propertydirect:admin"))&&!Boolean.TRUE.equals(s.getAttribute("dashboard:propertydirect:superadmin")))throw new IllegalStateException("Property administrator login is required");}
 private static boolean blank(String v){return v==null||v.isBlank();}private static boolean eq(String a,String b){return a!=null&&a.equalsIgnoreCase(b);}private static boolean contains(String a,String b){return a!=null&&a.toLowerCase(Locale.ROOT).contains(b.toLowerCase(Locale.ROOT));}private static String text(String v,String d){return blank(v)?d:v;}
 public record ListingRequest(@NotBlank String title,@NotBlank String society,@NotBlank String locality,@NotBlank String city,@NotBlank String type,String propertyType,@NotNull @Positive BigDecimal price,@PositiveOrZero BigDecimal deposit,@PositiveOrZero BigDecimal maintenance,@Positive Integer areaSqft,@NotBlank String bhk,String furnishing,String parking,LocalDate availableFrom,Double latitude,Double longitude,String amenities,String imageUrl,String notes){}
 public record EnquiryRequest(Long listingId,@NotBlank String name,@NotBlank String phone,@Email @NotBlank String email,@NotBlank String type,String message){}
 public record ContactMessageRequest(@NotBlank @Size(max=60) String firstName,@NotBlank @Size(max=60) String lastName,@Email @NotBlank @Size(max=160) String email,@NotBlank @Pattern(regexp="^[0-9+() -]{7,20}$",message="Enter a valid phone number") String phone,@NotBlank @Size(min=10,max=2000) String message){}
 public record SavedSearchRequest(@NotBlank String name,String city,String locality,String type,String bhk,@PositiveOrZero BigDecimal minPrice,@PositiveOrZero BigDecimal maxPrice,boolean alertsEnabled){}
 public record VisitRequest(@NotNull Long listingId,@NotNull@Future LocalDateTime scheduledAt,String notes){}
 public record ServiceRequest(Long listingId,@NotBlank String serviceType,@NotNull@Future LocalDateTime preferredAt,String details){}
}
